In [1]:
import numpy as np
import cvxpy as cp

## Example from cvxpy 

In [21]:
n = 3
p = 3

np.random.seed(1)

C = np.random.randn(n,n)
A = []
b = []

for i in range(p):
    A.append(np.random.randn(n,n))
    b.append(np.random.randn())

In [22]:
X = cp.Variable((n,n), symmetric = True)

constraints = [X >> 0]
constraints += [
    cp.trace(A[i] @ X) == b[i] for i in range(p)
]

In [23]:
prob = cp.Problem(cp.Minimize(cp.trace(C @ X)), constraints)
prob.solve()

2.6543470585557203

In [25]:
X.value

array([[ 1.60805504, -0.59770125, -0.69575821],
       [-0.59770125,  0.22228555,  0.24689067],
       [-0.69575821,  0.24689067,  1.39679134]])

## Example with quantum state

In [ ]:
rho = np.array([[0.5, 0.2, 0.1], [0.2, 0.3, 0.], [0.1, 0., 0.2]])

X = cp.Variable((3,3), hermitian = True) #setting hermitian makes cvxpy think entries are complex

constraints = [X>>0, cp.trace(X) == 1]

objective = cp.real(cp.trace(rho @ X)) #so we need to take real part here so no complex in objective fct

prob = cp.Problem(cp.Maximize(objective), constraints)
prob.solve()

0.6402685566554495

In [41]:
X.value

array([[0.71578654+0.j, 0.42071985+0.j, 0.16257992+0.j],
       [0.42071985+0.j, 0.24728669+0.j, 0.09556   +0.j],
       [0.16257992+0.j, 0.09556   +0.j, 0.03692677+0.j]])

In [43]:
rho_0 = np.array([[0.7, 0.2], [0.2, 0.3]])  # Example state 1
rho_1 = np.array([[0.4, 0.1], [0.1, 0.6]])  # Example state 2

E0 = cp.Variable((2,2), hermitian=True)
E1 = cp.Variable((2,2), hermitian = True)

constraints = [E0 >> 0, E1 >> 0, E0 + E1 == np.eye(2)]

objective = cp.real(0.5 * cp.trace(rho_0 @ E0) + 0.5 * cp.trace(rho_1 @ E1))

prob = cp.Problem(cp.Maximize(objective), constraints)
prob.solve()



np.float64(0.6581148607722879)

In [44]:
E0.value

array([[0.97434458+0.j, 0.15811486+0.j],
       [0.15811486+0.j, 0.02565544+0.j]])

In [47]:
d = 2

phip = np.array([[1, 0, 0, 1], 
                     [0, 0, 0, 0], 
                     [0, 0, 0, 0], 
                     [1, 0, 0, 1]]) / d


J = cp.Variable((d**2, d**2), hermitian = True)

constraints = [J >> 0, cp.partial_trace(J, (d,d), 1) == np.eye(d)]

objective = cp.real(cp.trace(phip @ J))

prob = cp.Problem(cp.Maximize(objective), constraints)
prob.solve()

2.0000000195088443

In [48]:
J.value

array([[ 1.00000001e+00+0.j, -1.42895070e-16+0.j,  3.39844948e-17+0.j,
         1.00000001e+00+0.j],
       [-1.42895070e-16+0.j, -6.49215334e-09+0.j, -4.50064862e-34+0.j,
        -3.41646567e-17+0.j],
       [ 3.39844948e-17+0.j, -4.50064862e-34+0.j, -6.49215029e-09+0.j,
        -7.47418209e-17+0.j],
       [ 1.00000001e+00+0.j, -3.41646567e-17+0.j, -7.47418209e-17+0.j,
         1.00000001e+00+0.j]])

In [55]:
y0 = cp.Variable()
y1 = cp.Variable()
y2 = cp.Variable()
y3 = cp.Variable()
y4 = cp.Variable()

M2 = cp.bmat([[y0,y1,y2],
              [y1,y2,y3],
              [y2,y3,y4]])
M1 = cp.bmat([[y0,y1],[y1,y2]])

constraints = [M2 >> 0, M1 >> 0, y0 == 1]
constraints += [y1 >= -1, y1 <= 1]
constraints += [y3 >= -1, y3 <= 1]
constraints += [y4 >= 0, y4 <= 1]



objective = y4 - 2*y2 + y1

prob = cp.Problem(cp.Maximize(objective), constraints)
prob.solve()

np.float64(1.125000232787867)